[INFO] 2018-04-14 15:27:07,641 PyPPSPP starting
[INFO] 2018-04-14 15:27:07,641 PPSPP Parameters:
        Tracker: 127.0.0.1;
        Running on Port: 2006;
        Filename: ./resource/factory-I-720p_files/factory-I-720p.seg2-L2.svc;
        Filesize: 991703B;
        Swarm: 4f68ff5b2455cc483d2e3f5332b23de0322941e3;
        Logger: ./resource/factory-I-720p_files/logs/factory-I-720p.seg2-L2.svcSeederPeer.log;
        Live: False;
        Live Source: False;
        Alto: False;
        Num peers: None;
        Identifier: None;
        Skip: False;
        DiscardWnd: 1000;
        Buffer Sz: 500;
        Dl Fwd: 0;
        VOD: False;
    
[WARNING] 2018-04-14 15:27:07,644 Exception connecting to tracker: [Errno 111] Connect call failed ('127.0.0.1', 6777)
[WARNING] 2018-04-14 15:27:08,646 Exception connecting to tracker: [Errno 111] Connect call failed ('127.0.0.1', 6777)
[WARNING] 2018-04-14 15:27:09,648 Exception connecting to tracker: [Errno 111] Connect call failed ('127.0.0.1', 6777)
[ERROR] 2018-04-14 15:27:10,650 Failed to connect to the tracker!
